### ISSUE TITLE
The "semantic cut"

### ISSUE THREAD

**Issue by borismarin** [tarelli/org.lemsml.model#21]
We need to decide at which point we "stop" extending the model (i.e. the classes in org.lemsml.model , automatically generated but extendable with the visitor machinery). Currently, the only other package down the  xml -> simulation pipeline is (part of) jLEMS. At which  "decoration" stage should org.neuroml.model stop, delegating further work to jLEMS?

Potential things to be considered:

- expression parsing 
  - building an AST
  - all the way from String to an "Evaluable" object
- dimensional analysis (maybe it should be under exp parsing...)
   - decorating all literals with Units (not for composite things involving expressions) 
   - checking expressions for dimensional consistency (involves the AST above?)
   - "adimensionalization" (i.e. selecting one system of units and stripping them off)
- flattening
- paths

All of those things can be achieved with more or less work using the "extension / decoration" approach. Ideally, simulator developers (or people doing codegen) would rely on org.lemsml.model to give them something "flexible" (many quotes)  enough to work with, so the more of those we shove into the model the better?

**Comment by pgleeson** [comment]
Bear in mind that whatever gets loaded into memory by the API should be convertible again losslessly to pure LEMS XML. So the first step is to get something very close in structure to the orig "model" as defined by the XML and most other steps will be optional depending on what the user wants to do. 

While expression parsing is fine if the original string expression can be retrieved/regenerated, no automatic flattening/dimension stripping should be done. 

Automated tests for this roundtripping should be incorporated sooner rather than later (unless you've already got them there...)

**Comment by borismarin** [comment]
I tend to think that expression parsing and dimensional validation belong in the model package, because since LEMS "understands" maths, syntactically (as in math syntax) incorrect formulae are also syntactically incorrect LEMS, and thus `1 1+` should generate parsing errors analog to what `<Lomponent>` would generate. The same for dimensionally incorrect expressions (speed * time != distance).

I also agree with @pgleeson on the roundtrip issue - and now, after spending pleasant afternoons studying Jaxb, I see how much easier life would have been if we had taken the "standard" (as in the majority of the examples out there) Jaxb path: start with the Java classes, and generate the schema from them (annotating as necessary). I'll add some roundtrip tests as soon as I finish a draft dimensional validation AST visitor for the parsed expressions. Or maybe @adrianq would like to give it a go?

**Comment by robertcannon** [comment]
Interesting - I hadn't realized that was the majority approach though I can see it would make life easier. So it means people are either just using a custom XML format specific to their project, or, if they are implementing a pre-existing standard, they are hand-coding the java, and tweaking it until the generated schema matches the standard schema. 

On the stopping point, I agree with Padraig that you shouldn't force dimension stripping on people, but I don't think that would ever be the intention? It is more a question of how much of the pipeline do you implement in lemsml.model, and how much do you leave for other packages? 

Thinking of oneself as the customer, I'd hope to get flattening, non-dimensionalization and unit handling from something called "libLEMS" but that doesn't mean it should all be in the model. 

On the other hand, my understanding of the jaxb approach is that it gives you an auto-generated visitor pattern that can be hoped to make these things easier to develop and test than just hand-coding them on  a hand-coded family of objects. That would suggest you should do them on the lemsml.model classes since those are the ones over which you have the visitors and presumably you don't want other people having to do that. 

Another way to look at it is that anything that is uniquely defined and for which, once it is done, there is little benefit in doing it a differently, should be done in libLems and probably on the model. So, obviously running a simulation is outside this scope since there are a multitude of ways of doing that each with their own strengths and weaknesses, but generating a dimensionless version of the model is inside, since there should only be one possible output. Flattening is  slightly grey area - as the reviewer said it can be an "unconstrained approximation" but I think you'd probably still want it as long as you can specify what gets flattened and what doesn't.
  
I'm not sure the expression parsing  should go as far as generating an evaluable object (except that you need this for dimension checking, though the object doesn't have to be exposed) but generating and AST would certainly be nice.

**Comment by borismarin** [comment]
After [reorganizing the code](https://github.com/tarelli/org.lemsml.model/commit/132a88614912c10672729a781b5f44b7c029fe92), it's very clear where and how to add new semantic analyzers to the parser. Whenever we decide something else should belong in the parser, a new specific card should be opened.
