### ISSUE TITLE
Error handling during parsing / validation

### ISSUE THREAD

**Issue by borismarin** [tarelli/org.lemsml.model#24]
We need to catch and inform (useful error msgs) parse errors for both malformed LEMS, math exprs, dimensionality, etc. I don't know if the standard practice in Java is throwing and catching exceptions, or letting them bubble up and break everything. Related to #15, #16.

**Comment by robertcannon** [comment]
It depends how you want to use it. If a model has an error, then it can't be run, so you could let it bubble up to the top and stop there.

The difficulty with this is that if there are a bunch of errors, the user only sees the first and has to fix that before they can move on to the next. So it depends to what extent you can meaningfully carry on. If it is malformed XML, you probably don't have much choice but to jump out at the first problem. If it is a bad expression,  you can flag it as dodgy and carry on with other expressions.

I'd like to catch all errors in jld and generate a comprehensive error report because I want to be able to use it like the continuous compiler in an IDE, but its not always possible: some errors leave things in such a mess that there's no point trying to continue.

**Comment by borismarin** [comment]
- [ ]  Design meaningful exception types for errors associated with each [semantic analysis pass] (https://github.com/tarelli/org.lemsml.model/blob/master/src/main/java/compiler/semantic/LEMSSemanticAnalyser.java#L31) (e.g. DimensionalAnalysisException)
- [ ] Make sure the associated visitor emits these Exceptions.

**Comment by borismarin** [comment]
Subcards?

**Comment by tarelli** [comment]
I added https://github.com/tarelli/org.lemsml.model/issues/30 which is relevant

**Comment by borismarin** [comment]
With the ideas from #30, visitors can now decorate any node with an error code; exceptions can also be used. Will open more specific as needed.
